#%RAML 1.0 Trait

description: Unique identifier for correlating API requests and responses
headers:
  X-Correlation-Id:
    type: string
    example: "dd960082-abbf-47c2-8c65-f18eeb35848b"
    required: true